config/routes.rb
Rails.application.routes.draw do

  resources :clientes
  resources :amortizations
  resources :loans

  root 'application#index'

    # Obtener Un Cliente con su monto prestado
    get 'getClienteMongo', to: 'clientes#getClienteMongo'

    #  Obtener Un Prestamo con su amortizacion
    get 'getPrestamo/:principal/(:interes)/:plazo', to: 'loans#getPrestamo', :constraints => {:interes => /[^\/]+/}

    #  Guardar un prestamo asignado a un cliente
    post 'guardarPrestamo', to: 'loans#guardarPrestamo'
    
    # Para ver los clientes
    #   /clientes => clientes#show

    # Para ver los prestamos
    #   /loans => loans#show
    
    # Para ver las amortizaciones
    #   /amortizations => amortizations#show
    
    # Path general para cuando no escriben bien una ruta
    # get '*path', to: 'application#index'
end

app/models/amortization.rb
class Amortization < ApplicationRecord
  belongs_to :loan

  validates_presence_of :no_pago, :saldo_insoluto, :monto_interes,:iva, :pago_capital, :pago_capital_con_intereses ,:fecha , :loan_id

  # Recibo 2 parametros, el prestamo y el arreglo de amortizaciones
  def guardarAmortizaciones(loan,amortizaciones)
    ActiveRecord::Base.transaction do
      success = false
      # Ciclo para guardar las amortizaciones
        amortizaciones.each do |amortizacion|
          @amortizacion = Amortization.new()
          @amortizacion.loan_id = loan.id
          @amortizacion.no_pago = amortizacion[:no_pago]
          @amortizacion.iva = amortizacion[:iva]
          @amortizacion.saldo_insoluto = amortizacion[:saldo_insoluto]
          @amortizacion.monto_interes = amortizacion[:interes]
          @amortizacion.pago_capital = amortizacion[:capital]
          @amortizacion.pago_capital_con_intereses = amortizacion[:pago_capital_con_intereses]
          @amortizacion.fecha = amortizacion[:fecha]
           if @amortizacion.save
            success = true
          end
        end
        # Retorno el resultado de la transaccion
      return success
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente
  attr_accessor :name, :loans, :prestado
  # MongoDB connection and attributes
#   include Mongoid::Document
#   include Mongoid::Timestamps
#   field :name, type: String
#   field :id, type: Integer

#   validates_presence_of :name
  # has_many :loans
end

app/models/loan.rb
class Loan < ApplicationRecord
  # belongs_to :cliente
  has_many :amortizations

  validates_presence_of :principal, :interes, :plazo, :cliente_id
end

app/controllers/amortizations_controller.rb
class AmortizationsController < ApplicationController

  # GET /amortizations or /amortizations.json
  def index
    @amortizations = Amortization.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index
        
    end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController

  # Obtener el cliente simulado
  def getClienteMongo

    # Se obtiene el cliente 
    cliente = Cliente.new
    cliente.name = 'Diego Gaxiola Development'
    # Se obtiene el prestamo del cliente llamando a la base de datos PostgreSQL
    cliente.loans = Loan.all
    cliente.prestado = cliente.loans.sum(:principal)
    
    render json: cliente
  end

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  def getPrestamo
    success = false
    # Se obtienen los parametros de la url del prestamo
    principal = params[:principal].to_i
    interes = params[:interes].to_f
    plazo = params[:plazo].to_i
    
    # Calculo el prestamo con FinanceMath::Loan
    @loan = FinanceMath::Loan.new(nominal_rate: interes, duration: plazo, amount: principal, structure_fee: 0, currency_protection: 0, fee: 0)
    
    # Calculos de Variables (formulas)
    monto_capital = @loan.principal.to_i
    pago_capital = (@loan.principal / @loan.duration)
    pago_capital_con_intereses = @loan.pmt.to_i
    pago_intereses = (pago_capital_con_intereses - pago_capital)
    monto_final_prestamo = (pago_capital_con_intereses * @loan.duration).to_i
    
    # Array que contendra las amortizaciones del prestamo
    @amortizacion = []
    monto_acumulado = 0
    monto_acumulado_con_intereses = 0

    # Ciclo para generar las amortizaciones
    (1..@loan.duration.to_i).each do |i|
      monto_acumulado += pago_capital
      saldo_insoluto = monto_capital - monto_acumulado
      monto_acumulado_con_intereses += pago_capital_con_intereses
      
      # Inserto Amortizaciones para el prestamo en el arreglo
      @amortizacion << {
        no_pago: i,
        saldo_insoluto:(saldo_insoluto.to_i),
        interes: pago_intereses.round,
        iva: (pago_intereses * 0.16).to_i,
        pago_capital: pago_capital.round,
        pago_capital_con_intereses: pago_capital_con_intereses.to_i,
        capital: pago_capital,
        fecha: (Date.today + (i.month)).strftime("%d/%m/%Y"),
        monto_acumulado: monto_acumulado,
        monto_acumulado_con_intereses: monto_acumulado_con_intereses,
      }
    end

    # Retorno el resultado de la transaccion
        render json: {
        loan:@loan,
        amortizacion:@amortizacion,
        apr:@loan.apr,
        pmt:@loan.pmt,
        pago_capital_con_intereses:pago_capital_con_intereses,
        intereses_totales:(pago_intereses * @loan.duration),
        monto_final_prestamo:monto_final_prestamo,
        }
  end

  # Guarda el prestamo en la base de datos
  def guardarPrestamo
    ActiveRecord::Base.transaction do
      success = false
      @loan = Loan.new()
      @loan.principal = params[:loan][:principal]
      @loan.interes = params[:loan][:nominal_rate]
      @loan.plazo = params[:loan][:duration]
      @loan.cliente_id = params[:cliente_id]

      if @loan.save
        # Guardo las amortizaciones llamando al modelo Amortizacion
       if Amortization.new.guardarAmortizaciones(@loan, params[:amortizacion])
          success = true
        end
      end
      # Si todo salio bien, se retorna true
      render json: { success:success }
    end
  end

end

app/helpers/amortizations_helper.rb
module AmortizationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/amortizations/_form.html.erb
<%= form_with(model: amortization) do |form| %>
  <% if amortization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amortization.errors.count, "error") %> prohibited this amortization from being saved:</h2>

      <ul>
        <% amortization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :loan_id %>
    <%= form.text_field :loan_id %>
  </div>

  <div class="field">
    <%= form.label :no_pago %>
    <%= form.number_field :no_pago %>
  </div>

  <div class="field">
    <%= form.label :saldo_insoluto %>
    <%= form.text_field :saldo_insoluto %>
  </div>

  <div class="field">
    <%= form.label :iva %>
    <%= form.text_field :iva %>
  </div>

  <div class="field">
    <%= form.label :pago_capital %>
    <%= form.text_field :pago_capital %>
  </div>

  <div class="field">
    <%= form.label :pago_capital_con_intereses %>
    <%= form.text_field :pago_capital_con_intereses %>
  </div>

  <div class="field">
    <%= form.label :monto_interes %>
    <%= form.text_field :monto_interes %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amortizations/edit.html.erb
<h1>Editing Amortization</h1>

<%= render 'form', amortization: @amortization %>

<%= link_to 'Show', @amortization %> |
<%= link_to 'Back', amortizations_path %>

app/views/amortizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amortizations</h1>

<table>
  <thead>
    <tr>
      <th>Loan</th>
      <th>No pago</th>
      <th>Saldo insoluto</th>
      <th>Iva</th>
      <th>Pago capital</th>
      <th>Pago capital con intereses</th>
      <th>Monto interes</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amortizations.each do |amortization| %>
      <tr>
        <td><%= amortization.loan_id %></td>
        <td><%= amortization.no_pago %></td>
        <td><%= amortization.saldo_insoluto %></td>
        <td><%= amortization.iva %></td>
        <td><%= amortization.pago_capital %></td>
        <td><%= amortization.pago_capital_con_intereses %></td>
        <td><%= amortization.monto_interes %></td>
        <td><%= amortization.fecha %></td>
        <td><%= link_to 'Show', amortization %></td>
        <td><%= link_to 'Edit', edit_amortization_path(amortization) %></td>
        <td><%= link_to 'Destroy', amortization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amortization', new_amortization_path %>

app/views/amortizations/new.html.erb
<h1>New Amortization</h1>

<%= render 'form', amortization: @amortization %>

<%= link_to 'Back', amortizations_path %>

app/views/amortizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan:</strong>
  <%= @amortization.loan_id %>
</p>

<p>
  <strong>No pago:</strong>
  <%= @amortization.no_pago %>
</p>

<p>
  <strong>Saldo insoluto:</strong>
  <%= @amortization.saldo_insoluto %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @amortization.iva %>
</p>

<p>
  <strong>Pago capital:</strong>
  <%= @amortization.pago_capital %>
</p>

<p>
  <strong>Pago capital con intereses:</strong>
  <%= @amortization.pago_capital_con_intereses %>
</p>

<p>
  <strong>Monto interes:</strong>
  <%= @amortization.monto_interes %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @amortization.fecha %>
</p>

<%= link_to 'Edit', edit_amortization_path(@amortization) %> |
<%= link_to 'Back', amortizations_path %>

app/views/application/index.html.erb
<%= javascript_pack_tag 'hello_react' %>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.name %></td>
        <td><%= cliente.id %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cliente.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @cliente.id %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuenteBuenaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loans/_form.html.erb
<%= form_with(model: loan) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :principal %>
    <%= form.text_field :principal %>
  </div>

  <div class="field">
    <%= form.label :interes %>
    <%= form.text_field :interes %>
  </div>

  <div class="field">
    <%= form.label :plazo %>
    <%= form.number_field :plazo %>
  </div>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.text_field :cliente_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>Principal</th>
      <th>Interes</th>
      <th>Plazo</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.principal %></td>
        <td><%= loan.interes %></td>
        <td><%= loan.plazo %></td>
        <td><%= loan.cliente_id %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Principal:</strong>
  <%= @loan.principal %>
</p>

<p>
  <strong>Interes:</strong>
  <%= @loan.interes %>
</p>

<p>
  <strong>Plazo:</strong>
  <%= @loan.plazo %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @loan.cliente_id %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>